concurrency:
  cancel-in-progress: ${{ github.ref_name != 'main' }}
  group: dependency-review-${{ github.ref }}
jobs:
  dependency-review:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
      with:
        egress-policy: audit
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Dependency Review
      uses: actions/dependency-review-action@9129d7d40b8c12c1ed0f60400d00c92d437adcce
name: Dependency Review
on:
  repository_dispatch:
    types: trigger-ga___dependency-review.yml
permissions:
  contents: read
