concurrency:
  cancel-in-progress: ${{ github.ref_name != 'main' }}
  group: ci-${{ github.ref }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
      with:
        egress-policy: audit
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -B -V -Dstyle.color=always clean verify
name: Maven Build
on:
  repository_dispatch:
    types: trigger-ga___maven-ci-and-prb.yml
permissions:
  contents: read
