jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
      with:
        egress-policy: audit
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      name: Perform docker login
      run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - continue-on-error: true
      env:
        GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
        GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}
      name: Import GPG key
      run: 'echo $GPG_SECRET_KEYS | base64 --decode | gpg --import --no-tty --batch
        --yes

        echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust --no-tty
        --batch --yes

        '
    - continue-on-error: true
      env:
        X_GITHUB_USERNAME: ${{ secrets.ADOBE_BOT_GITHUB_USERNAME  }}
      name: Configure git user for release commits
      run: 'git config user.email "Grp-opensourceoffice@adobe.com"

        git config user.name "${X_GITHUB_USERNAME}"

        '
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3
    - continue-on-error: true
      env:
        ADOBE_BOT_GITHUB_PASSWORD: ${{ secrets.ADOBE_BOT_GITHUB_PASSWORD }}
        ADOBE_BOT_GITHUB_USERNAME: ${{ secrets.ADOBE_BOT_GITHUB_USERNAME  }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      name: Release with Maven
      run: ./mvnw -B -V --settings ./.github/workflows/settings.xml release:prepare
        release:perform
name: Maven Release
on:
  repository_dispatch:
    types: trigger-ga___maven-release.yml
